# Generated by Django 4.1.7 on 2023-04-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_kecamatan_br1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan_br2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jk', models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=100)),
                ('tangga_lahir', models.CharField(max_length=100)),
                ('desa', models.CharField(max_length=100)),
                ('posyandu', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('status_KM', models.CharField(choices=[('Kurang Mampu', 'Kurang Mampu'), ('Tidak', 'Tidak')], max_length=100)),
                ('usia_ukur', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('tb', models.IntegerField()),
                ('bb_u', models.CharField(choices=[('Berat Badan Normal', 'Berat Badan Normal'), ('Kurang', 'Kurang'), ('Risiko Lebih', 'Risiko Lebih'), ('Sangat Kurang', 'Sangat Kurang')], max_length=100)),
                ('tb_u', models.CharField(choices=[('Normal', 'Normal'), ('Pendek', 'Pendek'), ('Tinggi', 'Tinggi'), ('Sangat Pendek', 'Sangat Pendek')], max_length=100)),
                ('bb_tb', models.CharField(choices=[('Gizi Kurang', 'Gizi Kurang'), ('Gizi Baik', 'Gizi Baik')], max_length=100)),
                ('stunting', models.CharField(choices=[('Potensi Stunting', 'Potensi Stunting'), ('Stunting', 'Stunting'), ('Tidak', 'Tidak')], max_length=100)),
            ],
        ),
    ]
