# Generated by Django 4.1.7 on 2023-04-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_kecamatan_br2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kecamatan_br2',
            name='bb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kecamatan_br2',
            name='tb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kecamatan_br2',
            name='usia_ukur',
            field=models.FloatField(),
        ),
    ]
