# Generated by Django 4.1.7 on 2023-04-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_data_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_training',
            name='alamat',
        ),
    ]
