# Generated by Django 4.1.7 on 2023-04-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_alter_data_prediksi_bb_tb_alter_data_prediksi_bb_u_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_prediksi',
            name='bb_tb',
            field=models.PositiveIntegerField(choices=[(0, 'Gizi Kurang'), (1, 'Gizi Baik')]),
        ),
        migrations.AlterField(
            model_name='data_prediksi',
            name='bb_u',
            field=models.PositiveIntegerField(choices=[(1, 'BB Normal'), (0, 'BB Kurang'), (2, 'BB Sangat Kurang')]),
        ),
        migrations.AlterField(
            model_name='data_prediksi',
            name='jk',
            field=models.PositiveIntegerField(choices=[(1, 'L'), (0, 'P')]),
        ),
        migrations.AlterField(
            model_name='data_prediksi',
            name='status_KM',
            field=models.PositiveIntegerField(choices=[(1, 'Kurang Mampu'), (0, 'Mampu')]),
        ),
        migrations.AlterField(
            model_name='data_prediksi',
            name='tb_u',
            field=models.PositiveIntegerField(choices=[(3, 'TB Tinggi'), (1, 'TB Normal'), (0, 'TB Pendek'), (2, 'TB Sangat Pendek')]),
        ),
        migrations.AlterField(
            model_name='data_prediksi',
            name='usia_ukur',
            field=models.PositiveIntegerField(choices=[(1, 'Lebih Dari 3 Tahun'), (0, '3 Tahun'), (2, 'Kurang Dari 3 Tahun')]),
        ),
    ]
