# Generated by Django 4.1.7 on 2023-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0011_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaBaru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan', models.CharField(max_length=100)),
                ('hari', models.CharField(max_length=100)),
            ],
        ),
    ]
